development:
  password: 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
  theme_id: "126615126131"
  store: corre-perro-mx/.myshopify.com
live:
  password: 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
  theme_id: "126615126131"
  store: corre-perro-mx/.myshopify.com